# Site settings
title: inha.logs 
header-img: img/home-bg.jpg
email: inhajoo9@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://ijoo2.github.io"
twitter_username: 
github_username: ijoo2 
facebook_username: inha.joo 
email_username: inhajoo9@gmail.com 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
